### ISSUE TITLE
Impressum

### ISSUE THREAD

**Issue by testgoofy** [EndressHauser-ProcessSolutions/simple-netilion-demo#3]
Eine legale Internetseite braucht ein Impressum.
Was es braucht: https://www.weka.ch/themen/marketing-verkauf/online-marketing/e-commerce/article/impressumspflicht-schweiz-so-erstellen-sie-rechtssichere-websites/

**Comment by JonasSchultheiss-EH** [comment]
Imprint has been added at the bottom of the page.
