### ISSUE TITLE
Mobile Ansicht

### ISSUE THREAD

**Issue by testgoofy** [EndressHauser-ProcessSolutions/simple-netilion-demo#4]
Die Mobile Ansicht ist noch nicht ganz ausgereift.

- input-field boxen für Login sind zu klein -> volle Breite und untereinander anzeigen
- dropdown ist zu kelein -> auch auf ganzer Breite anzeigen
- Tabelle wird nicht suaber dargestellt -> Unübersichtlich und abstände passen nicht
  - Header ist verschoben
  - Idee: Header bleibt an Seitenrand fixiert und nur die Valus werden gescrollt
![Unbenannt](https://user-images.githubusercontent.com/55271228/65142823-db4cfb80-da13-11e9-9abc-a3835332236b.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/55271228/65142898-00416e80-da14-11e9-8992-24480352110f.PNG)

**Comment by JonasSchultheiss-EH** [comment]
Daniel Haller meinte, dass die mobile Ansicht keine Priorität hat.

**Comment by testgoofy** [comment]
Wurde behoben
